
TASK_LOG_START = 1
TASK_LOG_POSTPONE = 2
TASK_LOG_DONE = 3
TASK_LOG_ARCHIVE = 4
TASK_LOG_CHANGED = 5
TASK_LOG_ENUM = {TASK_LOG_START : 'started', TASK_LOG_POSTPONE : 'postponed' , TASK_LOG_DONE : 'marked as done' , TASK_LOG_ARCHIVE : 'archived', TASK_LOG_CHANGED : 'changed'}

