# Generated by Django 3.0.dev20190315010523 on 2019-11-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Task period name')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Task period type')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('start_date', models.DateField(verbose_name='initial date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('period_data', models.IntegerField(default=0, verbose_name='Period data')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Period')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_date', models.DateField(verbose_name='next task date')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=0)),
                ('log_date', models.DateTimeField(verbose_name='action date')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Task')),
            ],
        ),
    ]
