# Generated by Django 3.0.dev20190315010523 on 2020-01-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Task'),
        ),
    ]
