# Generated by Django 3.0.dev20190315010523 on 2020-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200103_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='action date'),
        ),
    ]
