# Generated by Django 3.0.dev20190315010523 on 2020-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200217_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
