# Generated by Django 3.0.dev20190315010523 on 2020-12-07 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.BooleanField(default=False, verbose_name='By email'),
        ),
    ]
