# Generated by Django 3.0.dev20190315010523 on 2021-08-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201207_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
